name: Test and Deploy to Railway

on:
  push:
    branches: [main]  # Trigger on pushes to 'main'
  pull_request:
    branches: [main]  # Also test PRs against 'main'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest

  deploy:
    name: Deploy to Railway
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy on push to main

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy using Railway CLI
        uses: railwayapp/cli-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
